### ISSUE TITLE
java.sql.SQLException: Numeric Overflow a teszt indulásakor

### ISSUE THREAD

**Issue by ljszalai** [i-Cell-Mobilsoft-Open-Source/roaster#72]
Roaster 0.7.0
A teszt indulásakor a következő stack trace jelenik meg a logban:
```java
febr. 28, 2022 11:33:00 DE. org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl sequenceInformationList
ERROR: Could not fetch the SequenceInformation from the database
java.sql.SQLException: Numerikus túlcsordulás
	at oracle.jdbc.driver.NumberCommonAccessor.throwOverflow(NumberCommonAccessor.java:4139)
	at oracle.jdbc.driver.NumberCommonAccessor.getLong(NumberCommonAccessor.java:636)
	at oracle.jdbc.driver.GeneratedStatement.getLong(GeneratedStatement.java:208)
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getLong(GeneratedScrollableResultSet.java:261)
	at oracle.jdbc.driver.GeneratedResultSet.getLong(GeneratedResultSet.java:560)
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.resultSetMinValue(SequenceInformationExtractorLegacyImpl.java:134)
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:60)
...
```
Nem idéztem be a teljes stack trace-t, mivel reprodukálható bármely tetszőleges teszt futtatásával. 
A teszt lefut, de a log mérete jelentősen megnövekszik ezáltal.

Elvárt működés: 
A stack trace, ha nincs befolyása a teszt lefutására, ne jelenjen meg a logban! 
Megjegyzés:
A logolási beállítások változtatása, aminek eredményeként ez stack trace, illetve a Weld felfutása nem jelenik meg a logban elfogadható megoldás lehet, de jobb volna az okot megszűntetni.

**Comment by martin-nagy** [comment]
Ez nem Roaster hiba, a teszt projektben kellene orvosolni.

**Comment by rombow** [comment]
Az entity melyik reszeben hasznaltal sequnciat, ami tulcsordult?

**Comment by martin-nagy** [comment]
Nem használt. De a Hibernate induláskor lekérdezi az összes sequencia adatait, ami megváltozott a verzióváltás következtében. Elég, ha a DB sémában van egy sequence, aminek a min_value-ja nem fér bele a long-ba.
